swagger: '2.0'
info:
  description: '测试描述'
  version: 1.0.0
  title: Abc
host: petstore.swagger.io
schemes:
  - http
paths:

  /sw/api_abc/Abc/CrAbc:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/CreateAbcRequest'
      responses:
        '200':
          description:	successful operation
          schema:
            $ref: '#/definitions/CreateAbcReply'
  /sw/api_abc/Abc/ss:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/CreateAbcRequest'
      responses:
        '200':
          description:	successful operation
          schema:
            $ref: '#/definitions/CreateAbcReply'


definitions:

  CreateAbcRequest:
    type: object
    properties:

      a:
        type: string
        format: string
      ai:
        type: integer
        format: int32
      nt:
        type: object
        format: object
  CreateAbcReply:
    type: object
    properties:

      b:
        type: integer
        format: int32
      r:
        type: string
        format: string
  Sub:
    type: object
    properties:

      addr:
        type: string
        format: string


externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

